[package]
cairo-version = "=2.8.4"
name = "dojo_examples"
version = "1.0.0-alpha.8"
# Use the prelude with the less imports as possible
# from corelib.
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
build-external-contracts = [ "armory::Flatbow", "bestiary::RiverSkale" ]

[dependencies]
armory = { path = "../game-lib/armory" }
bestiary = { path = "../game-lib/bestiary" }
dojo = { path = "../../crates/dojo/core" }
#dojo_plugin = { path = "../../crates/dojo/lang" }

[features]
default = [ "dungeon" ]
dungeon = [  ]

[profile.saya]
