[package]
edition.workspace = true
name = "katana-primitives-macros"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0"
starknet.workspace = true
syn = { version = "2.0", features = [ "fold", "full" ] }
