[package]
cairo-version = "2.7.0"
edition = "2024_07"
description = "The Dojo Core library for autonomous worlds."
name = "dojo"
version = "1.0.0-alpha.4"

[dependencies]
starknet = "=2.7.0"

[dev-dependencies]
dojo_plugin = { git = "https://github.com/dojoengine/dojo", rev = "f15def33" }

[lib]
