[package]
edition.workspace = true
license.workspace = true
license-file.workspace = true
name = "katana-tracing"
repository.workspace = true
version.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
